repository:
  name: todogit-ios
  description: A GitHub open source client for iOS
  homepage: https://todogit.io
  private: true
  has_issues: true
  has_wiki: false
  has_downloads: true
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
labels:
collaborators: