included:
  - iOS
  - macOS
  - Frameworks
excluded:
  - Assets
  - .build
  - Carthage
disabled_rules:
  - trailing_whitespace
  - nesting
  - cyclomatic_complexity
  - file_length
  - todo
line_length:
  warning: 150
  error: 170
