osx_image: xcode9
language: objective-c
notifications:
  email: false
before_install:
- bundle install
- brew upgrade swiftlint
- brew upgrade carthage
script:
- bundle exec rake ci
after_success:
  - bash <(curl -s https://codecov.io/bash)